spring:
  application:
    name: feijitang
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  profiles:
    active: dev
datasource:
  druid:
    url: jdbc:mysql://192.168.31.137:3306/feijitang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: root
    filters: stat,slf4j
    initialSize: 10
    maxActive: 100
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000 # 检查空闲连接周期
    minEvictableIdleTimeMillis: 300000 #空闲超过300秒则回收
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
logging:
  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.leiyu.feijitang.model
  check-config-location: true
  config-location: classpath:mybatis.xml